name: pdebuild-bionic

on:
  pull_request:
    branches: main

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Create the build environment using pbuilder 
      run:  |       
        sudo apt update
        sudo apt install debian-keyring ubuntu-keyring pbuilder curl gnupg2 lsb-release -y
        sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key F42ED6FBAB17C654
        sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key CADA0F77901522B3
        curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
        ls -al /etc/apt/trusted.gpg.d
        cp .github/workflows/pbuilderrc-bionic.conf /home/runner/.pbuilderrc
        sudo pbuilder create
